### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by jdcaballerov** [conbus/fbmq#16]
Hi, 

I recently implemented the bot example using django. However the fb send api returned an error of internal failure related to oauth. 

`{"error":{"message":"(#-1) Send API unexpected internal error","type":"OAuthException","code":-1,"error_subcode":2018012,"fbtrace_id":"BZ8p\/q9haBY"}}`

The problem is related to the [message object](https://developers.facebook.com/docs/messenger-platform/send-api-reference#message) ,as you might read, text must be UTF-8 encoded and less than 640char.

All the library is beautifully written and respects UNICODE, however text must be encoded as follows:

`page.send(sender_id,message.encode('utf-8'))`

so that it can reliably echo back text messages.

If you agree I can make a pull request modifying Page.send(..) such that

`text = message if isinstance(message, str) else None 
`
is changed for

`text = message if isinstance(message, str) else message.encode('utf-8') if isinstance(message,unicode) else None`

This will allow it to support unicode strings and respect facebook´s api.

**Comment by kimwz** [comment]
Thank you @jdcaballerov.
I agree with you.
Please send a merge request. I will approve after a few tests.

**Comment by kimwz** [comment]
Thanks merged.

**Comment by 610** [comment]
@kimwz @jdcaballerov This commit is incompatible with Python3, since `unicode` type was removed there.
Now I get "NameError: name 'unicode' is not defined" error if I try to send a template.

**Comment by havardgulldahl** [comment]
I suggest reopening this. I don't think the fix was the best one. 

There are errors for py3, and I have some working sample code to revert the code from #17 for py3. It works for me in production. 

I think you should look at this again. :D

**Comment by kimwz** [comment]
Thank you all. fixed
