### ISSUE TITLE
when send in text, both text and attachment got check up

### ISSUE THREAD

**Issue by antigenius0910** [conbus/fbmq#19]
AFTER_SEND : {"message": {"attachment": "test", "metadata": null, "quick_replies": null, "text": "test"}, "notification_type": null, "recipient": {"id": "1208595212586466", "phone_number": null}, "sender_action": null}

RESPONSE : {"error":{"message":"(#100) Only one of text or attachment can be specified","type":"OAuthException","code":100,"error_subcode":2018018,"fbtrace_id":"Ft9OlIgxEe4"}}
127.0.0.1 - - [06/Mar/2017 21:03:57] "POST /webhook HTTP/1.1" 200 -

**Comment by kimwz** [comment]
thank you. fixed.
