### ISSUE TITLE
Can't get example to work

### ISSUE THREAD

**Issue by xicore** [conbus/fbmq#20]
I have been trying all morning to get the example 'server.py' to work. I followed the instructions per the README.md file as follows:

pip install fbmq
cd example
virtualenv env
source env/bin/activate
pip install -r requirements.txt
python server.py

I am on Ubuntu 14.04 using python2.7

I get the following error:

env) michaels@michaels-ThinkPad-W520:~/work/python/plugins/fbmq/example$ python server.py 
Traceback (most recent call last):
  File "server.py", line 8, in <module>
    import example.messenger
ImportError: No module named example.messenger

**Comment by kimwz** [comment]
@xicore 
You did it right. I don't know why it doesn't work.

Try below another way
```
cd example
touch __init__.py
python server.py
```

**Comment by xicore** [comment]
The source code imports from 'example.messenger' but the project root is already in 'example' I also see that in previous versions of this example the path 'example.' is not used.

**Comment by xicore** [comment]
ok. it works now with the touch __init__.py
it seems that this is necessary as when I do 'pip install fbmq' it also attempts to install the modules in the example directory. Without the __init__.py Python does not install and that was the problem.
This is a bug that must be fixed. Just add an empty __init__.py in examples and we're done.
Thanks

**Comment by kimwz** [comment]
@xicore Thanks. fixed it

**Comment by xicore** [comment]
Hi Karl,

I am trying to work through the server example, which seems awesome. I am
new to Python and Facebook apps and am having difficulty getting the
various server examples to run. What do I need to do to see the various
menus, icons and buttons appear on my messenger page. I have my bot app
validated and I am getting and sending text messages.

BR
