### ISSUE TITLE
Message Sending Error

### ISSUE THREAD

**Issue by daxeel** [conbus/fbmq#21]
I am getting this error,

{"error":{"message":"(#-1) Send API unexpected internal error","type":"OAuthException","code":-1,"error_subcode":2018012,"fbtrace_id":"CQMDI4deN+O"}}

**Comment by itsiky** [comment]
It seems like you're missing a parameter on the request to Facebook api. 

can you attach the request sent to the API?

**Comment by oliver-daniel** [comment]
Hi @daxeel ,

After wrestling with this very problem for over two hours, I've discovered that Unicode is to blame. Make sure you're explicitly converting all received text into strings using str(). I don't know why this is happening, but it is. Cheers!

**Comment by Rdbaker** [comment]
Is this issue going to be fixed? I had to debug it for a while and got the same error. It was pretty painful and incredibly opaque to understand what was going wrong

**Comment by aflock** [comment]
It looks like the issue actually was fixed in https://github.com/conbus/fbmq/commit/e65e3e749bbaff80e80c4e161c18524dbf34d69f , but the pip package has not been updated since 2016-09-07, so if you're using pip you'll still run into this issue. 

@kimwz any chance to bump the pip package version?

**Comment by kimwz** [comment]
@aflock thank you. I uploaded v2.0.2 to the pip

**Comment by daxeel** [comment]
Awesome work guys. @oliver-daniel @aflock @kimwz
