### ISSUE TITLE
Referral callback support

### ISSUE THREAD

**Issue by DonnaRosa** [conbus/fbmq#26]
Hello!
I'd be glad to see a referral callback support. I've tried to add support myself, so you can freely use this patch as a starting point.

Best regards,

[fbmq_referral.patch.txt](https://github.com/conbus/fbmq/files/1194906/fbmq_referral.patch.txt)

**Comment by kimwz** [comment]
Thank you @DonnaRosa.
Could you please make a PR?

**Comment by anton-nayshtut** [comment]
@DonnaRosa is it the same functionality as introduced by 739c2efb1aa83357115e175ef2b1718a0b532ca6?

Please advise.

**Comment by DonnaRosa** [comment]
Hello! Yes I believe this is the same  functionality. Thanks for letting know!

**Comment by anton-nayshtut** [comment]
@DonnaRosa Thank you!
