### ISSUE TITLE
not able to select api version

### ISSUE THREAD

**Issue by lalomx** [conbus/fbmq#32]
library always uses v2.6 although v2.10 is now available

**Comment by auvipy** [comment]
yes exactly. 2.10 should be minimal

**Comment by auvipy** [comment]
https://github.com/conbus/fbmq/pull/35

**Comment by wessilfie** [comment]
any update on this? could potentially update the invocation of new page object to include version number and leave the default to 2.6

**Comment by anton-nayshtut** [comment]
@wessilfie see #44 ([release 2.4.2](https://pypi.python.org/pypi/fbmq/2.4.2))
