### ISSUE TITLE
Does not play nice with classes

### ISSUE THREAD

**Issue by mpschr** [conbus/fbmq#40]
I just wanted to raise the issue. I created a class that I mount in cherryp. Unluckily the decorators do not play nice with the classes.

Do you know how to get around that?

Example: 

`class FBBot(object):
    def __init__(self):
        self.config = {}

    @cherrypy.expose()
    def webhook(self, *args, **kwargs):

        try:
            if cherrypy.request.method == "GET" and 'hub.verify_token' in kwargs and kwargs['hub.verify_token'] == VERIFY_TOKEN:
                return int(kwargs['hub.challenge'])
        except ValueError:
             return 'Invalid verification token'

        cl = cherrypy.request.headers['Content-Length']
        payload = cherrypy.request.body.read(int(cl)).decode()

        print("FBBOT + {}".format(payload))
        page.handle_webhook(payload)
        return 'ok'

    @page.handle_message
    def message_handler(self, event):
        """:type event: fbmq.Event"""
        sender_id = event.sender_id
        message = event.message_text`

when the `message_handler` function is called, the `self` is creating a problem:

> 
> 2017-10-26T14:55:38.120444+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 670, in respond
> 2017-10-26T14:55:38.120445+00:00 app[web.1]:     response.body = self.handler()
> 2017-10-26T14:55:38.120445+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
> 2017-10-26T14:55:38.120446+00:00 app[web.1]:     self.body = self.oldhandler(*args, **kwargs)
> 2017-10-26T14:55:38.120447+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
> 2017-10-26T14:55:38.120448+00:00 app[web.1]:     return self.callable(*self.args, **self.kwargs)
> 2017-10-26T14:55:38.120448+00:00 app[web.1]:   File "/app/random_match/bot/facebook.py", line 44, in webhook
> 2017-10-26T14:55:38.120449+00:00 app[web.1]:     page.handle_webhook(payload,message=self.message_handler)
> 2017-10-26T14:55:38.120449+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/fbmq/fbmq.py", line 219, in handle_webhook
> 2017-10-26T14:55:38.120450+00:00 app[web.1]:     self._call_handler('message', message, event)
> 2017-10-26T14:55:38.120451+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/fbmq/fbmq.py", line 183, in _call_handler
> 2017-10-26T14:55:38.120451+00:00 app[web.1]:     self._webhook_handlers[name](*args, **kwargs)
> 2017-10-26T14:55:38.120452+00:00 app[web.1]: TypeError: message_handler() missing 1 required positional argument: 'event'

**Comment by JosXa** [comment]
I'd like to add a related concern to this issue:
I'm trying to build an abstraction around the core functionality of my bot (initialization, sending messages, ...) and the only supported way to add routing definitions currently is to use decorators. What I do now is to replicate what the decorators do internally in my abstraction, so for example to add a plaintext message handler I add the webhook handler for messages into the protected `_webhook_handlers` field of a page (`self.page._webhook_handlers['message'] = my_callback`), which obviously causes my IDE to complain about access to a protected member of the `page` object.

It would be nice to have a method exposed that allows us to add handlers to the internal `webhook_handlers`, something like:
`def add_handler(scope, callback): ...`

I don't know how active the development is on this lib, so if you respond to this issue then I'd be willing to make a PR :smile:

**Comment by JosXa** [comment]
> I don't know how active the development is on this lib, so if you respond to this issue then I'd be willing to make a PR :smile:

Nevermind, PR submitted anyway ¯\_(ツ)_/¯
