### ISSUE TITLE
Supporting Message Tags?

### ISSUE THREAD

**Issue by wobedi** [conbus/fbmq#48]
Hey there,

Awesome library!

Do you guys support Message Tags yet?

https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags

Couldn't find anything in the docs.

Thanks,
Yanick

**Comment by anton-nayshtut** [comment]
Hi Yanick,

Message Tags are currently not supported.

Please open an issue and I'll try to handle it.

Thanks,
Anton

**Comment by wobedi** [comment]
Cool! Done:

https://github.com/conbus/fbmq/issues/48

*Yanick Steinbeck*
Skype: YanickSTE
*Find me on LinkedIn*
<http://ch.linkedin.com/pub/yanick-steinbeck/86/b09/248>
