### ISSUE TITLE
Handling Multiple pages?

### ISSUE THREAD

**Issue by michaelhjulskov** [conbus/fbmq#55]
How is it possible to handle multiple pages?
Anyone done that?

**Comment by anton-nayshtut** [comment]
What to you mean? You can always create 2 or more instances of the **Page** class - one instance per page.
```python
page1 = Page(PAGE1_ACCESS_TOKEN)
page2 = Page(PAGE2_ACCESS_TOKEN)
...
```

**Comment by michaelhjulskov** [comment]
ahh that way :)
Perfect, thank You
