### ISSUE TITLE
Postbacks being ignored

### ISSUE THREAD

**Issue by Pedrat** [conbus/fbmq#58]
I'm developing a python bot with this module. And when i'm working with postback buttons, get started button, or the persistent menu, it doesn't do anything. Even in the logs it doesn't appear, could someone help?

>`page.show_starting_button("START_PAYLOAD")`

 `@page.callback(['START_PAYLOAD'])
def start_callback(payload="START_PAYLOAD"):
  print("Let's start!Test")` #Callback

Help would be appreciated

**Comment by michaelhjulskov** [comment]
Hi
Have you tried:
```
@page.callback(['START_PAYLOAD'])
def start_callback(): 
    print("Let's start!")
```

**Comment by michaelhjulskov** [comment]
Hi
Have you tried:
```

@page.callback(['START_PAYLOAD'])
def start_callback(): 
    print("Let's start!")
```

getting any errors?

also you need to make sure your app settings is correct
in Messenger - > Settings -> Webhooks I have : messaging_referrals, messages, messaging_postbacks
and make sure your page is shown right below where it says "Subscribed pages: "

is the bot working with other messages?

did you ping the page.show_starting_button("GET_STARTED") ?
if yes maybe ping the page.hide_starting_button() and retry again

**Comment by Pedrat** [comment]
Yes i did try it, it didn't work, and it did answer the messages.
But i got it working, i was missing the permission setting of message_postback on the webhook settings, thank you ! :+1:

**Comment by michaelhjulskov** [comment]
You're welcome :-)
