### ISSUE TITLE
There is no referral handler - error form FBMQ 

### ISSUE THREAD

**Issue by fr1sk** [conbus/fbmq#68]
Hi, I have my own handler, but is it possible to disable this message or how to create referral handler that is doing nothing (just logging something for example)

**Comment by HwangWonYo** [comment]
Hi,

1. If you want to disable [messaging_referrals](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_referrals) webhook event, you should uncheck messaging_referrals in webhook settings.

2. If you want to create referral handler that is doing nothing, add this code below.
```python
@page.handle_referral
def referral_handler(event):
    pass
```

**Comment by fr1sk** [comment]
Thanks, second one is what I was looking for! 🍻
