### ISSUE TITLE
In the usage, change event.message_text to event.message!

### ISSUE THREAD

**Issue by dqdang** [conbus/fbmq#69]
I keep forgetting that event.message_text is now event.message and whenever I look back at the usage, I grab the wrong variable. Thanks!

**Comment by HwangWonYo** [comment]
I agree. ReadMe should be updated or fbmq should support message_text too. Why don't you make PR for this?

**Comment by dqdang** [comment]
Sorry for the delay. Just created a pull request for the changes.
